spin_manifest_version = "1"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "A collection of WASM components to facilitate easier use of weather data from AWS Open Data."
name = "spinwx"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spinwx"
source = "app.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"

[[component]]
id = "gfs-latest-available"
source = "gfs-latest-available/gfs_latest.wasm"
allowed_http_hosts = ["insecure:allow-all"]

[component.trigger]
route = "/gfs/latest"
[component.build]
command = "spin py2wasm gfs_latest -o gfs_latest.wasm"
workdir = "gfs-latest-available"

[[component]]
id = "gfs-idx"
source = "gfs-idx/gfs_idx.wasm"
allowed_http_hosts = ["insecure:allow-all"]

[component.trigger]
route = "/gfs/idx/..."
[component.build]
command = "spin py2wasm gfs_idx -o gfs_idx.wasm"
workdir = "gfs-idx"

[[component]]
id = "gfs-grib"
source = "gfs-grib/gfs_grib.wasm"
allowed_http_hosts = ["insecure:allow-all"]

[component.trigger]
route = "/gfs/grib/..."
[component.build]
command = "spin py2wasm gfs_grib -o gfs_grib.wasm"
workdir = "gfs-grib"
